### ISSUE TITLE
Blob vs. File use in createEntity method of BaseClient

### ISSUE THREAD

**Issue by awk** [onshape-public/java-client#21] opened 2020-01-13 12:49 UTC
(From a third-party developer)

Now this error (see below) seems to be in your java-client code. I noticed that the .file() call in blobElements builder method was changed to Blob (instead of File). But, in the createEntity method of BaseClient (as shown below) you are still checking for File type. This should have been Blob.class. Isn’t it?

```
Entity createEntity(Object payload, Builder invocationBuilder) throws OnshapeException {
Field fileField = null;
Field[] var5 = payload.getClass().getDeclaredFields();
int var6 = var5.length;

int var7;
for(var7 = 0; var7 < var6; ++var7) {
Field field = var5[var7];
if (File.class.equals(field.getType())) {
fileField = field;
}
}
```

**Comment by treddy16** [comment] 2020-01-17 07:20
The issue is we are getting "Unsupported media type" exception.

com.onshape.api.exceptions.OnshapeException: Unsupported Media Type

	at com.onshape.api.base.BaseClient.call(BaseClient.java:480)
	at com.onshape.api.base.BaseClient.call(BaseClient.java:321)
	at com.onshape.api.requests.BlobElementsUploadFileCreateElementRequest$Builder.call(BlobElementsUploadFileCreateElementRequest.java:659)

When I traced this to the source, I see that the Content-Type header is set to multipart/formdata based on the condition that the field is of type File. But the input is of type Blob in the API call?

**Comment by harmanpa** [comment] 2020-01-17 09:19
Thanks for identifying and reporting that @treddy16, you are right that it was attempting to upload JSON not a multipart form. This repository is generated from https://github.com/onshape-public/api-generator and the PR https://github.com/onshape-public/api-generator/pull/37 fixes this issue, so once that is merged and built it will regenerate the client with this method fixed.

**Comment by raghuram-reddy** [comment] 2020-01-17 16:32
I just pulled the latest version and the error is gone.
 
Now I am getting a different error (not much useful information in the error message):

com.onshape.api.exceptions.OnshapeException: Bad Request
 
            at com.onshape.api.base.BaseClient.call(BaseClient.java:505)
            at com.onshape.api.base.BaseClient.call(BaseClient.java:333)
            at com.onshape.api.requests.TranslationsCreateTranslationRequest$Builder.call(TranslationsCreateTranslationRequest.java:527)
            at com.cassinisys.pdm.TestOnshape.testOnshape(TestOnshape.java:32)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
            at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
            at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
            at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
            at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
            at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
            at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
            at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
            at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
            at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
            at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
            at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
            at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
            at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
            at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
            at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
            at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
            at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
 
 
Here is my code:
 
@Test
public void testOnshape() throws Exception {
    Onshape onshape = new Onshape();
    String accessKey = "?????";
    String secretKey = "?????";
    onshape.setAPICredentials(accessKey, secretKey);

    File f = new File("/Users/reddy/Downloads/drill-press-11.snapshot.1/flange.SLDPRT");
    TranslationsCreateTranslationResponse response = onshape.translations()
            .createTranslation()
            .file(new Blob(f))
            .yAxisIsUp(Boolean.FALSE)
            .storeInDocument(true)
            .formatName("solidworks")
            .flattenAssemblies(Boolean.FALSE)
            .call("58b5957c5dda440f8447cb92", "32a8a8bd865ea7ae1fe8c9eb");

    System.out.println(response.getHref());
}

**Comment by harmanpa** [comment] 2020-01-18 10:04
Sorry this is also a related issue, as the client is failing to tell the server the filename it is deciding that it is not a supported source type. We will apply a fix for this but also add some additional tests for the file upload methods as they are currently missed.

Though also in your example code - the formatName field is for the destination type, so this is currently requesting a translation from Solidworks to Solidworks?

**Comment by raghuram-reddy** [comment] 2020-01-19 06:25
Regarding the format name, I should be using ONSHAPE then because I am trying to convert a Solidworks file to Onshape.

**Comment by raghuram-reddy** [comment] 2020-01-26 04:30
Any update on this issue? When can we expect a fix?

**Comment by harmanpa** [comment] 2020-01-26 10:29
@raghuram-reddy I'm just testing a fix. I expect to submit a PR for review on Monday. If there's iteration on the PR it may take a few days - I'm in different timezone (UK) to Onshape team.

**Comment by raghuram-reddy** [comment] 2020-02-01 02:13
The latest updated fixed the issue. Thank you!

**Comment by harmanpa** [comment] 2020-02-01 11:31
@raghuram-reddy thanks for confirming, please feel free to report any other issues or improvement requests here

**Closed by harmanpa** 2020-02-01 11:31 UTC
