### ISSUE TITLE
Exception on Documents -> Download External Data

### ISSUE THREAD

**Issue by mthiesmeyer** [onshape-public/java-client#1] opened 2019-02-14 14:41 UTC
A user is seeing the following exception when trying to download the result of a translation operation.

Reproduction Steps:
- Create a translation of an assembly using Assemblies.createTranslation
- Once the response _requestState_ is _DONE_ (you may need to poll the _href_ returned in the response).
- Call Documents.downloadExternalData with the _resultExternalDataIds_ from the response.

```
Exception in thread "main" com.onshape.api.exceptions.OnshapeException: Unable to convert media-type application/octet-stream;charset=utf-8 to type class com.onshape.api.responses.DocumentsDownloadExternalDataResponse
	at com.onshape.api.base.BaseClient.call(BaseClient.java:294)
	at com.onshape.api.requests.DocumentsDownloadExternalDataRequest$Builder.call(DocumentsDownloadExternalDataRequest.java:72)
	at us.ihmc.robotics.robotDescription.cad.onShape.OnShapeModelDownloadExample.main(OnShapeModelDownloadExample.java:39)```

**Comment by dljsjr** [comment] 2019-02-14 15:53
Thanks for opening this issue @mthiesmeyer!

The above is accurate. Using the Java client library I am able to request a translation for an assembly, and when the translation completes I *can* access the Collada XML using the API Explorer but when I attempt to make a call to `Onshape#documents()downloadExternalData().call(String, String)` I get the above exception.

**Comment by harmanpa** [comment] 2019-02-14 16:13
This is caused by incorrectly assigning the "Data" type in the API spec to be a Map, when in fact it should be handled specially, as files currently are. The offending line is here:
https://github.com/onshape-public/api-generator/blob/ef5b204479f889f3b7cf759bdd4fabe8a88f01e3/onshape-java/api-generator/src/main/java/com/onshape/api/generator/java/JavaLibraryTarget.java#L241

I'll fix this in api-generator, the Java client will be updated when the build is run.

**Comment by ethan92429** [comment] 2019-02-14 16:17
Thanks @harmanpa - I'll kick off the build as soon as you make the change.

**Comment by harmanpa** [comment] 2019-02-14 16:59
@ethan92429 The "Data" type is also referenced for "items.0.featureSpec" in the response for the Documents.insertables method, what is the actual content-type of that field?

**Comment by ethan92429** [comment] 2019-02-15 13:21
featureSpec is also an object. Checkout the call [here](https://cad.onshape.com/api/partstudios/d/6f19383069c3ff9b470753e8/w/8ca520d94a429ff02dde511b/e/85d45b93d761821b7d44efb6/featurespecs)

**Comment by harmanpa** [comment] 2019-03-13 16:01
@dljsjr Could you try the new build, v1.93.23050.f7e220beef3f, and see if it fixes the issue you discovered please?

**Comment by dljsjr** [comment] 2019-03-18 15:33
@harmanpa Sorry for the delayed response, I'll try it out today or tomorrow and let you know.

**Comment by dljsjr** [comment] 2019-03-19 15:32
@harmanpa I can confirm that in the new build I am able to download the .dae file from the translation! Thanks for looking at this @harmanpa @ethan92429 !

**Comment by harmanpa** [comment] 2019-03-20 11:43
Closing as offline tests and user feedback show working

**Closed by harmanpa** 2019-03-20 11:43 UTC
